spring.datasource.password= mysqlpass123@!
#spring.jpa.open-in-view=true
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

logging.level.org.springframework.web=DEBUG